### PR TITLE
Reduce live server start time

### PR DESCRIPTION
**Pull request by vitalk**
Another approach used to reduce live server start time.

- Completely remove `time.sleep` timeouts between checks. Use socket to ensure the server is up.

- Fail test case when server is not available after `--live-server-wait` timeout.

### CODE REVIEW

**Comment by vitalk** [comment]
@jadkik the current implementation uses `socket` to check server availability and completely remove sleep timeout.

**Comment by jadkik** [comment]
@vitalk awesome, seems it's just as fast on my test suite.

**Comment by hackebrot** [comment]
Hey @vitalk! 👋 

Thank you for your work on pytest-flask 🙇 

Is this PR expected to land any time soon? Anything I can do to help?

**Comment by northernSage** [comment]
I have chipped in and resolved the conflicts, hope it's okay. Is there any reason keeping us from merging this that I'm not seeing here or am I free to do so?

**Comment by northernSage** [comment]
I have updated the changelog since this ended up not being released in `0.10.0`. Not sure if this should be `1.1.0` or a major release, though, since now we have "--live-server-wait" and LiveServer has changed considerably.

**Comment by nicoddemus** [comment]
`1.1.0` seems good thanks!

Let's merge this, has been waiting long enough. Thanks for finishing up!

**Pull request merged**
