### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by nicoddemus**
Also add conda-forge badge to the README

### CODE REVIEW

**Comment by nicoddemus** [comment]
Also replaced the "downloads" badge by a "Python versions" badge, as the downloads badge is no longer supported

**Comment by nicoddemus** [comment]
The README can be seen here: https://github.com/nicoddemus/pytest-flask/tree/release-0.11.0

**Comment by nicoddemus** [comment]
Thanks @vitalk, the idea is usually to first push a tag to the branch before merging, but no worries I'm doing that now. 👍

**Comment by nicoddemus** [comment]
Here's the job that will deploy the package: https://travis-ci.org/pytest-dev/pytest-flask/builds/421156185

**Comment by vitalk** [comment]
@nicoddemus thanks a lot!

**Comment by nicoddemus** [comment]
[Deployed](https://pypi.org/project/pytest-flask) 😁

**Pull request merged**
