### PR TITLE
Add --live-server-port option

### PR DESCRIPTION
**Pull request by RazerM**
My use case is that another service has to redirect to the one under test with a statically known port.

### CODE REVIEW

**Comment by RazerM** [comment]
I guess #81 will fix the Travis errors

**Comment by nicoddemus** [comment]
> I guess #81 will fix the Travis errors 

Yep! 👍 

We plan to merge lingering PRs and make a new release this weekend.

**Comment by RazerM** [comment]
I somehow missed #63, but probably because that PR is about two different issues. FWIW, I don't think reading the value from `app.config` is the right approach.

**Comment by nicoddemus** [comment]
@RazerM I merged your branch with the latest `master` and updated the CHANGELOG.

Thanks again for the PR!

**Comment by vitalk** [comment]
@RazerM, @nicoddemus thanks!

**Pull request merged**
